repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        args: [--package, nba_scraper]
        additional_dependencies:
          - types-python-dateutil
          - types-pyyaml
        files: ^src/

  - repo: local
    hooks:
      - id: pytest-quick
        name: pytest-quick
        entry: pytest
        language: system
        args: [-q, --disable-warnings, -W, "error"]
        stages: [manual]
        pass_filenames: false