name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,test]
        pip install ruff mypy types-python-dateutil types-pyyaml
    
    - name: Lint with ruff
      run: |
        ruff check .
    
    - name: Type check with mypy
      run: |
        mypy src --package nba_scraper
    
    - name: Test with pytest
      run: |
        pytest -q --disable-warnings -W error::DeprecationWarning:src.nba_scraper -W ignore:ARC4\ has\ been\ moved\ to\ cryptography.hazmat.decrepit.ciphers.algorithms.ARC4:CryptographyDeprecationWarning -ra --cov=src --cov-report=term-missing
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-${{ matrix.python-version }}
        path: .coverage